作業目標<br>
活用矩陣運算，實做線性代數<br>
作業重點<br>
線性代數公式應用<br>
矩陣相乘維度需要對好，例如:2X3矩陣乘上3X5矩陣得到2X5矩陣

題目:<br>
array1 = np.array([[10, 8], [3, 5]]) <br>
1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
2. 運用上列array計算特徵值、特徵向量?
3. 運用上列array計算SVD?

In [1]:
import numpy as np

In [4]:
#1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array1 = np.array([[10, 8], [3, 5]])
array2 = np.linalg.inv(array1)
print(array1*array2)

[[ 1.92307692 -2.46153846]
 [-0.34615385  1.92307692]]


In [10]:
#2. 運用上列array計算特徵值、特徵向量?
eigenvalue1, eigenvector1 = np.linalg.eig(array1)
eigenvalue2, eigenvector2 = np.linalg.eig(array2)
print(eigenvalue1, eigenvector1)
print(eigenvalue2, eigenvector2)


[13.  2.] [[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


In [ ]:
#3. 運用上列array計算SVD?

In [14]:
u1, s1, vh1 = np.linalg.svd(array1)
u2, s2, vh2 = np.linalg.svd(array2)
print("array1:")
print(u1,s1,vh1)
print("array2:")
print(u2,s2,vh2)


array1:
[[-0.91663818 -0.39971796]
 [-0.39971796  0.91663818]] [13.94721714  1.86417116] [[-0.74319741 -0.6690722 ]
 [-0.6690722   0.74319741]]
array2:
[[-0.6690722   0.74319741]
 [ 0.74319741  0.6690722 ]] [0.53643143 0.07169889] [[-0.39971796  0.91663818]
 [ 0.91663818  0.39971796]]
